server:
  port: 8761

spring:
  application:
    name: service-registry
  
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
   hostname: localhost
   preferIpAddress: true  
   