FROM eclipse-temurin:17.0.4.1_1-jre
EXPOSE 8081
ADD target/department-service-0.0.1-SNAPSHOT.jar department-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "department-service-0.0.1-SNAPSHOT.jar"]